In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
import os

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [4]:
X_train.shape

(404, 13)

In [5]:
X_valid.shape

(102, 13)

In [6]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [7]:
y_train[0]

15.2

In [8]:
model = Sequential()
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(1, activation='linear'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Batc  (None, 16)               64        
 hNormalization)                                                 
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

In [10]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [11]:
output_dir = 'model_output/'

In [12]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [18]:
if not os.path.exists(output_path):
  os.makedirs(output_path)
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
save_weights_only=True) # otherwise full model is saved
tensorboard = TensorBoard(log_dir='logs/' + run_name)
model.fit(X_train, y_train,
batch_size=8, epochs=32, verbose=1,
validation_data=(X_valid, y_valid),
callbacks=[modelcheckpoint, tensorboard])

Epoch 1/32
51/51 [==============================] - 0s 5ms/step - loss: 41.1755 - val_loss: 44.1216
Epoch 2/32
51/51 [==============================] - 0s 5ms/step - loss: 36.8589 - val_loss: 95.3406
Epoch 3/32
51/51 [==============================] - 0s 5ms/step - loss: 38.9207 - val_loss: 42.1243
Epoch 4/32
51/51 [==============================] - 0s 4ms/step - loss: 44.2532 - val_loss: 780.5920
Epoch 5/32
51/51 [==============================] - 0s 5ms/step - loss: 41.1665 - val_loss: 39.2050
Epoch 6/32
51/51 [==============================] - 0s 4ms/step - loss: 41.5693 - val_loss: 36.5401
Epoch 7/32
51/51 [==============================] - 0s 4ms/step - loss: 50.2340 - val_loss: 43.8381
Epoch 8/32
51/51 [==============================] - 0s 4ms/step - loss: 42.0375 - val_loss: 39.3575
Epoch 9/32
51/51 [==============================] - 0s 4ms/step - loss: 42.3159 - val_loss: 109.2259
Epoch 10/32
51/51 [==============================] - 0s 3ms/step - loss: 38.1122 - val_loss: 57.81

In [15]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [16]:
y_valid[42]

14.1

In [17]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 [==============================] - 0s 110ms/step


array([[18.509872]], dtype=float32)